# Generated by Django 6.0.1 on 2026-02-26 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_unified_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_experiences', to='hackathon.employee')),
            ],
            options={
                'db_table': 'employee_past_experiences',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
